apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  # kafka cluster name
  name: edh
spec:
  kafka:
    # broker version
    version: 3.2.0
    # initial replicas
    replicas: 3
    # provision lbs
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    #      - name: external
    #        port: 9094
    #        type: loadbalancer
    #        tls: false
    rack:
      topologyKey: topology.kubernetes.io/zone
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 1G
      -Xmx: 2G
    config:
      default.replication.factor: 3
      num.partitions: 15
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.2"
      inter.broker.protocol.version: "3.2"
      log.retention.hours: 2160
    storage:
      type: ephemeral
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "Kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: dedicated
                      operator: In
                      values:
                        - Kafka
    # resource limitation
    # -xms -xmx set as same as resources [limit]
    resources:
      requests:
        memory: 1Gi
        cpu: "250m"
      limits:
        memory: 3Gi
        cpu: "500m"
  # zookeeper information
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    resources:
      # requests and limits
      requests:
        memory: 256Mi
        cpu: "250m"
      limits:
        memory: 512Mi
        cpu: "500m"
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
