apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen-mysql
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: repository/yamls/app/gen_mysql/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true