apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: cicd
spec:
  destination:
    name: ""
    namespace: gateway
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.konghq.com"
    targetRevision: 2.11.0
    chart: kong
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ingressController.installCRDs
          value: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
