apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kappa-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vsvale/kappa_k8s_config.git
    targetRevision: HEAD
    path: prd
  destination:
    server: https://kubernetes.default.svc
    namespace: kappa
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: True
