apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  volumeName: research-vol
  resources:
    requests:
      storage: 8Gi