apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diesel-to-landing
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: repository/code/processing/spark/energy-case/landing/diesel/sparkapplication/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true