apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starboard-exporter
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: starboard-system
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://giantswarm.github.io/giantswarm-catalog"
    targetRevision: 0.5.1
    chart: starboard-exporter
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
