apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: repository/helm-charts/database/mysql-operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true