apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starboard-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://giantswarm.github.io/giantswarm-catalog"
    targetRevision: 0.5.1
    chart: starboard-exporter
  destination:
    server: "https://kubernetes.default.svc"
    namespace: starboard-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
