apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-ingestion
  namespace: cicd
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: repository/yamls/ingestion/metrics
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
