apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-registry
  namespace: cicd
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  project: default
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: repository/helm-charts/ingestion/cp-schema-registry
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
