apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-broker
  namespace: cicd
spec:
  destination:
    name: ""
    namespace: ingestion
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: "yamls/ingestion/broker/"
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
