apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    name: ""
    namespace: security
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 2.6.0
    chart: sealed-secrets
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
