apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-server
  name: argocd-server-nodeport
  namespace: cicd
spec:
  ports:
    - nodePort: 30443
      port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
