annotations:
  category: CMS
apiVersion: v2
appVersion: 5.22.4
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  tags:
  - ghost-database
  version: 9.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Ghost is an open source publishing platform designed to create blogs,
  magazines, and news sites. It includes a simple markdown editor with preview, theming,
  and SEO built-in to simplify editing.
home: https://github.com/bitnami/charts/tree/main/bitnami/ghost
icon: https://bitnami.com/assets/stacks/ghost/img/ghost-stack-220x234.png
keywords:
- ghost
- blog
- http
- web
- application
- nodejs
- javascript
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: ghost
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/ghost
- https://www.ghost.org/
version: 19.1.30
