apiVersion: v1
kind: Namespace
metadata:
  name: orchestrator

---
apiVersion: v1
kind: Namespace
metadata:
  name: database

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingestion

---
apiVersion: v1
kind: Namespace
metadata:
  name: processing

---
apiVersion: v1
kind: Namespace
metadata:
  name: datastore

---
apiVersion: v1
kind: Namespace
metadata:
  name: deepstorage

---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: viz

---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd

---
apiVersion: v1
kind: Namespace
metadata:
  name: security

---
apiVersion: v1
kind: Namespace
metadata:
  name: app

---
apiVersion: v1
kind: Namespace
metadata:
  name: cost

---
apiVersion: v1
kind: Namespace
metadata:
  name: misc

---
apiVersion: v1
kind: Namespace
metadata:
  name: dataops

---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
