---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-subchart
  namespace: cicd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gateway
  project: default
  source:
  path: gateway/kong/yamls
    repoURL: https://github.com/vsvale/kappa_k8s_config
    targetRevision: master
  sync:
    comparedTo:
      destination:
        namespace: gateway
        server: https://kubernetes.default.svc
      source:
        path: gateway/kong/yamls
        repoURL: https://github.com/vsvale/kappa_k8s_config
        targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
