apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-subchart
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
    path: "gateway/kong/yamls/manifests/"
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  sync:
    comparedTo:
      destination:
        namespace: gateway
        server: https://kubernetes.default.svc
      source:
        path: "gateway/kong/yamls/manifests/"
        repoURL: "https://github.com/vsvale/kappa_k8s_config.git"
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
