apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

#      - name: tls
#        port: 9093
#        type: internal
#        tls: true
# Security
#        authentication:
#          type: scram-sha-512
# External
#      - name: external
#        port: 9094
#        type: loadbalancer
#        tls: true
# Security
#        authentication:
#          type: scram-sha-512
# Security
#    authorization:
#      type: simple
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      num.partitions: 15
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
      log.message.format.version: "3.2"
      log.retention.hours: 2160
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    storage:
      type: ephemeral
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl: {}
