{{- if .Values.ingress.enabled}}
apiVersion: {{include "ingress.apiVersion" .}}
kind: Ingress
metadata:
  name:  {{include "fullname" .}}
  labels:
    app: {{include "fullname" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    component: "lenses"
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    lenses.io/app: {{include "fullname" .}}
    lenses.io/app.type: lenses-ingress
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end}}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations}}
    {{$key}}: {{$value | quote}}
  {{- end}}
spec:
  {{- if .Values.ingress.ingressClassName}}
  ingressClassName: {{.Values.ingress.ingressClassName | quote}}
  {{- end}}
  rules:
  - host: {{.Values.ingress.host | quote}}
    http:
      paths:
      - path: "/"
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"}}
        pathType: Prefix
        backend:
          service:
            name: {{include "fullname" . | quote}}
            port:
              number: {{.Values.servicePort}}
        {{- else}}
        backend:
          serviceName: {{include "fullname" . | quote}}
          servicePort: {{.Values.servicePort}}
        {{- end}}
  {{- if .Values.ingress.tls.enabled}}
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote}}
      {{- if .Values.ingress.tls.secretName}}
      secretName: {{ .Values.ingress.tls.secretName}}
      {{- else}}
      secretName: {{ include "fullname" . | quote}}
      {{- end}}
  {{- end -}}
{{- end -}}
