apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vsvale/kappa_k8s_config.git'
    path: repository/helm-charts/logging/elasticsearch
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true