apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: diesel-to-landing
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "vsvale/diesel-to-landing:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/diesel-to-landing.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "http://minio.deepstorage.svc.Cluster.local:9000"
    "fs.s3a.access.key": "LBGipuLnLkJgwjXE"
    "fs.s3a.secret.key": "WjnPIFgPIhsjeFSgyvo0vurlMNfjDWyV"

  driver:
    # cores: 1
    coreRequest: 250m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 1.0.0
    serviceAccount: default
  executor:
    # cores: 1
    coreRequest: 250m
    instances: 2
    memory: "512m"
    labels:
      version: 1.0.0