{{- if .Values.istioIngress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.istioIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ $svcPort }}
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istioIngress.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}