{{- if .Values.istioIngress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.istioIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
  {{- range .Values.istioIngress.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ $fullName }}
  http:
  - match:
      - uri:
          prefix: "/"
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $svcPort }}
{{- end }}