apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappa
spec:
  selector:
    matchLabels:
      app: kappa
  template:
    metadata:
      labels:
        app: kappa
    spec:
      containers:
        - name: kappa
          image: wesleywillians/argocd-fullcycle:latest
          ports:
            - containerPort: 8080
