apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: cicd
spec:
  destination:
    name: ""
    namespace: ingestion
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://strimzi.io/charts/"
    targetRevision: 0.30.0
    chart: strimzi-kafka-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
