apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: vinicius.vale
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Permissions
      - resource:
          type: topic
          name: src-mssql-advtw-json
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: src-mssql-advtw-json
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: src-mssql-advtw-json
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: src-mssql-advtw-json
          patternType: literal
        operation: Read
        host: "*"