apiVersion: v1
appVersion: 0.2.5
description: Apache Pinot is a realtime distributed OLAP datastore, which is used
  to deliver scalable real time analytics with low latency. It can ingest data from
  offline data sources (such as Hadoop and flat files) as well as online sources (such
  as Kafka). Pinot is designed to scale horizontally.
home: https://pinot.apache.org/
keywords:
- olap
- analytics
- database
- pinot
maintainers:
- email: dev@pinot.apache.org
  name: pinot-dev
name: pinot
sources:
- https://github.com/apache/pinot
version: 0.2.5
