apiVersion: v1
kind: Service
metadata:
  name: svc-lb-nginx
  namespace: example
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx-nginx-ingress
