apiVersion: v1
kind: Service
metadata:
  name: svc-lb-mongodb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
  namespace: database
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
     app.kubernetes.io/component: mongos
     app.kubernetes.io/instance: mongodb