apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kong
  namespace: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 8685
    targetPort: 80
  selector:
     app.kubernetes.io/instance: kong
     app.kubernetes.io/name: kong